name: Deploy

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/brutalzinn/discord/boberto"

    - name: Adicionado chave do Discord
      uses: appleboy/ssh-action@master
      env:
        DISCORD_KEY: ${{ secrets.DISCORD }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DISCORD_KEY, DISCORD_URL
        script: |
          sudo rm -f .env
          echo "DISCORD_TOKEN=$DISCORD_KEY" >/home/brutalzinn/discord/boberto/.env
          echo "DISCORD_URL=$DISCORD_URL" >>/home/brutalzinn/discord/boberto/.env

    - name: Disparando notificação no Discord pré deploy
      uses: appleboy/ssh-action@master
      env:
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DISCORD_URL
        script: |
          DATA=$(date '+%d-%m-%Y %H:%M:%S') &&
          CONTENT="Preparando para atualizar o boberto... - $DATA" &&
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"'"$CONTENT"'"}' $DISCORD_URL

    - name: Executando versão nova
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script_stop: true
        script: |
          cd /home/brutalzinn/discord/boberto
          bash start_boberto.sh

    - name: Disparando notificação no Discord
      uses: appleboy/ssh-action@master
      env:
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DISCORD_URL
        script: |
          DATA=$(date '+%d-%m-%Y %H:%M:%S') &&
          CONTENT="O deploy do boberto foi um sucesso. $DATA" &&
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"'"$CONTENT"'"}' $DISCORD_URL

    